package com.my.bbs;

import java.util.Date;

public class my_bbs_db {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.publish_user_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Long publishUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_title
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private String postTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_category_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Integer postCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_category_name
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private String postCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_status
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Byte postStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_views
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Long postViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_comments
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Long postComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_collects
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Long postCollects;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.last_update_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.create_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bbs_post.post_content
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    private String postContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_id
     *
     * @return the value of tb_bbs_post.post_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_id
     *
     * @param postId the value for tb_bbs_post.post_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.publish_user_id
     *
     * @return the value of tb_bbs_post.publish_user_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Long getPublishUserId() {
        return publishUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.publish_user_id
     *
     * @param publishUserId the value for tb_bbs_post.publish_user_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPublishUserId(Long publishUserId) {
        this.publishUserId = publishUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_title
     *
     * @return the value of tb_bbs_post.post_title
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_title
     *
     * @param postTitle the value for tb_bbs_post.post_title
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_category_id
     *
     * @return the value of tb_bbs_post.post_category_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Integer getPostCategoryId() {
        return postCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_category_id
     *
     * @param postCategoryId the value for tb_bbs_post.post_category_id
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostCategoryId(Integer postCategoryId) {
        this.postCategoryId = postCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_category_name
     *
     * @return the value of tb_bbs_post.post_category_name
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public String getPostCategoryName() {
        return postCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_category_name
     *
     * @param postCategoryName the value for tb_bbs_post.post_category_name
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostCategoryName(String postCategoryName) {
        this.postCategoryName = postCategoryName == null ? null : postCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_status
     *
     * @return the value of tb_bbs_post.post_status
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Byte getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_status
     *
     * @param postStatus the value for tb_bbs_post.post_status
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostStatus(Byte postStatus) {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_views
     *
     * @return the value of tb_bbs_post.post_views
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Long getPostViews() {
        return postViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_views
     *
     * @param postViews the value for tb_bbs_post.post_views
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostViews(Long postViews) {
        this.postViews = postViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_comments
     *
     * @return the value of tb_bbs_post.post_comments
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Long getPostComments() {
        return postComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_comments
     *
     * @param postComments the value for tb_bbs_post.post_comments
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostComments(Long postComments) {
        this.postComments = postComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_collects
     *
     * @return the value of tb_bbs_post.post_collects
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Long getPostCollects() {
        return postCollects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_collects
     *
     * @param postCollects the value for tb_bbs_post.post_collects
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostCollects(Long postCollects) {
        this.postCollects = postCollects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.last_update_time
     *
     * @return the value of tb_bbs_post.last_update_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.last_update_time
     *
     * @param lastUpdateTime the value for tb_bbs_post.last_update_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.create_time
     *
     * @return the value of tb_bbs_post.create_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.create_time
     *
     * @param createTime the value for tb_bbs_post.create_time
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bbs_post.post_content
     *
     * @return the value of tb_bbs_post.post_content
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bbs_post.post_content
     *
     * @param postContent the value for tb_bbs_post.post_content
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }
}