package com.my.bbs;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class my_bbs_dbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public my_bbs_dbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostIdIsNull() {
            addCriterion("post_id is null");
            return (Criteria) this;
        }

        public Criteria andPostIdIsNotNull() {
            addCriterion("post_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostIdEqualTo(Long value) {
            addCriterion("post_id =", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotEqualTo(Long value) {
            addCriterion("post_id <>", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThan(Long value) {
            addCriterion("post_id >", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThanOrEqualTo(Long value) {
            addCriterion("post_id >=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThan(Long value) {
            addCriterion("post_id <", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThanOrEqualTo(Long value) {
            addCriterion("post_id <=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdIn(List<Long> values) {
            addCriterion("post_id in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotIn(List<Long> values) {
            addCriterion("post_id not in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdBetween(Long value1, Long value2) {
            addCriterion("post_id between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotBetween(Long value1, Long value2) {
            addCriterion("post_id not between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNull() {
            addCriterion("publish_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIsNotNull() {
            addCriterion("publish_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdEqualTo(Long value) {
            addCriterion("publish_user_id =", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotEqualTo(Long value) {
            addCriterion("publish_user_id <>", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThan(Long value) {
            addCriterion("publish_user_id >", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("publish_user_id >=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThan(Long value) {
            addCriterion("publish_user_id <", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdLessThanOrEqualTo(Long value) {
            addCriterion("publish_user_id <=", value, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdIn(List<Long> values) {
            addCriterion("publish_user_id in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotIn(List<Long> values) {
            addCriterion("publish_user_id not in", values, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdBetween(Long value1, Long value2) {
            addCriterion("publish_user_id between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPublishUserIdNotBetween(Long value1, Long value2) {
            addCriterion("publish_user_id not between", value1, value2, "publishUserId");
            return (Criteria) this;
        }

        public Criteria andPostTitleIsNull() {
            addCriterion("post_title is null");
            return (Criteria) this;
        }

        public Criteria andPostTitleIsNotNull() {
            addCriterion("post_title is not null");
            return (Criteria) this;
        }

        public Criteria andPostTitleEqualTo(String value) {
            addCriterion("post_title =", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotEqualTo(String value) {
            addCriterion("post_title <>", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleGreaterThan(String value) {
            addCriterion("post_title >", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleGreaterThanOrEqualTo(String value) {
            addCriterion("post_title >=", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLessThan(String value) {
            addCriterion("post_title <", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLessThanOrEqualTo(String value) {
            addCriterion("post_title <=", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleLike(String value) {
            addCriterion("post_title like", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotLike(String value) {
            addCriterion("post_title not like", value, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleIn(List<String> values) {
            addCriterion("post_title in", values, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotIn(List<String> values) {
            addCriterion("post_title not in", values, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleBetween(String value1, String value2) {
            addCriterion("post_title between", value1, value2, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostTitleNotBetween(String value1, String value2) {
            addCriterion("post_title not between", value1, value2, "postTitle");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdIsNull() {
            addCriterion("post_category_id is null");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdIsNotNull() {
            addCriterion("post_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdEqualTo(Integer value) {
            addCriterion("post_category_id =", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdNotEqualTo(Integer value) {
            addCriterion("post_category_id <>", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdGreaterThan(Integer value) {
            addCriterion("post_category_id >", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("post_category_id >=", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdLessThan(Integer value) {
            addCriterion("post_category_id <", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("post_category_id <=", value, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdIn(List<Integer> values) {
            addCriterion("post_category_id in", values, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdNotIn(List<Integer> values) {
            addCriterion("post_category_id not in", values, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("post_category_id between", value1, value2, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("post_category_id not between", value1, value2, "postCategoryId");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameIsNull() {
            addCriterion("post_category_name is null");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameIsNotNull() {
            addCriterion("post_category_name is not null");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameEqualTo(String value) {
            addCriterion("post_category_name =", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameNotEqualTo(String value) {
            addCriterion("post_category_name <>", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameGreaterThan(String value) {
            addCriterion("post_category_name >", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("post_category_name >=", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameLessThan(String value) {
            addCriterion("post_category_name <", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("post_category_name <=", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameLike(String value) {
            addCriterion("post_category_name like", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameNotLike(String value) {
            addCriterion("post_category_name not like", value, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameIn(List<String> values) {
            addCriterion("post_category_name in", values, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameNotIn(List<String> values) {
            addCriterion("post_category_name not in", values, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameBetween(String value1, String value2) {
            addCriterion("post_category_name between", value1, value2, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostCategoryNameNotBetween(String value1, String value2) {
            addCriterion("post_category_name not between", value1, value2, "postCategoryName");
            return (Criteria) this;
        }

        public Criteria andPostStatusIsNull() {
            addCriterion("post_status is null");
            return (Criteria) this;
        }

        public Criteria andPostStatusIsNotNull() {
            addCriterion("post_status is not null");
            return (Criteria) this;
        }

        public Criteria andPostStatusEqualTo(Byte value) {
            addCriterion("post_status =", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusNotEqualTo(Byte value) {
            addCriterion("post_status <>", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusGreaterThan(Byte value) {
            addCriterion("post_status >", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("post_status >=", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusLessThan(Byte value) {
            addCriterion("post_status <", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusLessThanOrEqualTo(Byte value) {
            addCriterion("post_status <=", value, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusIn(List<Byte> values) {
            addCriterion("post_status in", values, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusNotIn(List<Byte> values) {
            addCriterion("post_status not in", values, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusBetween(Byte value1, Byte value2) {
            addCriterion("post_status between", value1, value2, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("post_status not between", value1, value2, "postStatus");
            return (Criteria) this;
        }

        public Criteria andPostViewsIsNull() {
            addCriterion("post_views is null");
            return (Criteria) this;
        }

        public Criteria andPostViewsIsNotNull() {
            addCriterion("post_views is not null");
            return (Criteria) this;
        }

        public Criteria andPostViewsEqualTo(Long value) {
            addCriterion("post_views =", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsNotEqualTo(Long value) {
            addCriterion("post_views <>", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsGreaterThan(Long value) {
            addCriterion("post_views >", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsGreaterThanOrEqualTo(Long value) {
            addCriterion("post_views >=", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsLessThan(Long value) {
            addCriterion("post_views <", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsLessThanOrEqualTo(Long value) {
            addCriterion("post_views <=", value, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsIn(List<Long> values) {
            addCriterion("post_views in", values, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsNotIn(List<Long> values) {
            addCriterion("post_views not in", values, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsBetween(Long value1, Long value2) {
            addCriterion("post_views between", value1, value2, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostViewsNotBetween(Long value1, Long value2) {
            addCriterion("post_views not between", value1, value2, "postViews");
            return (Criteria) this;
        }

        public Criteria andPostCommentsIsNull() {
            addCriterion("post_comments is null");
            return (Criteria) this;
        }

        public Criteria andPostCommentsIsNotNull() {
            addCriterion("post_comments is not null");
            return (Criteria) this;
        }

        public Criteria andPostCommentsEqualTo(Long value) {
            addCriterion("post_comments =", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsNotEqualTo(Long value) {
            addCriterion("post_comments <>", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsGreaterThan(Long value) {
            addCriterion("post_comments >", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsGreaterThanOrEqualTo(Long value) {
            addCriterion("post_comments >=", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsLessThan(Long value) {
            addCriterion("post_comments <", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsLessThanOrEqualTo(Long value) {
            addCriterion("post_comments <=", value, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsIn(List<Long> values) {
            addCriterion("post_comments in", values, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsNotIn(List<Long> values) {
            addCriterion("post_comments not in", values, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsBetween(Long value1, Long value2) {
            addCriterion("post_comments between", value1, value2, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCommentsNotBetween(Long value1, Long value2) {
            addCriterion("post_comments not between", value1, value2, "postComments");
            return (Criteria) this;
        }

        public Criteria andPostCollectsIsNull() {
            addCriterion("post_collects is null");
            return (Criteria) this;
        }

        public Criteria andPostCollectsIsNotNull() {
            addCriterion("post_collects is not null");
            return (Criteria) this;
        }

        public Criteria andPostCollectsEqualTo(Long value) {
            addCriterion("post_collects =", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsNotEqualTo(Long value) {
            addCriterion("post_collects <>", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsGreaterThan(Long value) {
            addCriterion("post_collects >", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsGreaterThanOrEqualTo(Long value) {
            addCriterion("post_collects >=", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsLessThan(Long value) {
            addCriterion("post_collects <", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsLessThanOrEqualTo(Long value) {
            addCriterion("post_collects <=", value, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsIn(List<Long> values) {
            addCriterion("post_collects in", values, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsNotIn(List<Long> values) {
            addCriterion("post_collects not in", values, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsBetween(Long value1, Long value2) {
            addCriterion("post_collects between", value1, value2, "postCollects");
            return (Criteria) this;
        }

        public Criteria andPostCollectsNotBetween(Long value1, Long value2) {
            addCriterion("post_collects not between", value1, value2, "postCollects");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bbs_post
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 11 15:16:44 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bbs_post
     *
     * @mbg.generated Tue Jun 11 15:16:44 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}